### ISSUE TITLE
Making reservation request for accommodation

### ISSUE THREAD

**Issue by panicmilos** [ftrip-io/booking-service#1]
Svaki zahtev mora da sadrži smeštaj, početni i krajnji datum rezervacije i broj gostiju. Kada se zahtev potvrdi od strane vlasnika smeštaja, kreira serezervacija i niko drugi ne može da šalje zahtev za isti smeštaj u istom vremenskom intervalu. Za neki smeštaj može postojati više zahteva u preklapajućim vremenskim intervalima koji čekaju odgovor.

Guest koji je kreirao zahtev za rezervaciju može ga obrisati pre nego što dobije odgovor.

**Comment by draganaF** [comment]
With the merge of PR #10  we can consider this issue as Done
