### ISSUE TITLE
Accepting reservation request

### ISSUE THREAD

**Issue by panicmilos** [ftrip-io/booking-service#3]
Host za neki smeštaj može odabrati automatsku ili ručnu potvrdu rezervacije. Ako je aktivirana automatska potvrda, svaki zahtev se prihvata čim pristigne. Ako je aktivna ručna potvrda, host može da prihvati ili odbije zahtev. Uz svaki zahtev mu se za guest-a prikazuje koliko puta u prošlosti je otkazao neku rezervaciju na platformi. Ako se zahtev potvrdi, svi ostali zahtevi čiji datumi se preklapaju sa prihvaćenim zahtevom treba da budu automatski odbijeni.

**Comment by draganaF** [comment]
With the merge of #8 , we can consider this Issue as Done.
